name: AVR make
description: Build avr based project with avr toolchain
author: Denis Bazhenov <dotsid@gmail.com>
branding:
  icon: terminal
  color: black
inputs:
  dir:
    description: directory in which to run make
    default: '.'
    required: false
    type: string
  target:
    description: target to make
    default: '--debug' # dummy option that has no impact; default target will be selected
    required: false
    type: string
env:
  #ARGS_ENV: ${{ inputs.dir!=null && ['--directory=AVR_Code','01'] || ['--directory=AVR_Code'] }}
  ARGS_ENV: ['--directory=AVR_Code','01']
runs:
  using: docker
  image: docker://lpodkalicki/avr-toolchain
  entrypoint: make 
  args:
    - '--directory=${{inputs.dir}}'
    - ${{inputs.target}}
