name: AVR make
description: Build avr based project with avr toolchain
author: Denis Bazhenov <dotsid@gmail.com>
branding:
  icon: terminal
  color: black
inputs:
  dir:
    description: directory in which to run make
    default: '.'
    required: false
    type: string
  target:
    description: target to make
    default: ''
    required: false
    type: string
jobs:
  build-default-target:
    if: "${{ inputs.dir == '' }}"
    runs:
      using: docker
      image: docker://lpodkalicki/avr-toolchain
      entrypoint: make 
      if 
      args: ['--directory=${{inputs.dir}}']
  build-selected-target:
    if: "${{ inputs.dir != '' }}"
    runs:
      using: docker
      image: docker://lpodkalicki/avr-toolchain
      entrypoint: make 
      if 
      args: ['--directory=${{inputs.dir}}','${{inputs.target}}']
